
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: mysql+asyncmy://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}

    volumes:
      - ./app:/app

    networks:
      - default

    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
