name: build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run tests with mocks
        env:
          PYTHONPATH: ./app
        run: |
          pytest -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CI }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/cristian-sangucho-a/conversational-sistem-v1:latest
          docker push ghcr.io/cristian-sangucho-a/conversational-sistem-v1:latest
